checkstyle:
plugins/EQ_Alert.py:7:1: F401 'os' imported but unused
plugins/EQ_Alert.py:10:1: F811 redefinition of unused 'json' from line 6
plugins/EQ_Alert.py:10:1: H306  imports not in alphabetical order (plugins, json)
plugins/EQ_Alert.py:84:27: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:84:28: E262 inline comment should start with '# '
plugins/EQ_Alert.py:93:1: W293 blank line contains whitespace
plugins/EQ_Alert.py:98:15: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:98:16: E262 inline comment should start with '# '
plugins/EQ_Alert.py:111:17: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:111:18: E262 inline comment should start with '# '
plugins/EQ_Alert.py:112:66: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:112:67: E262 inline comment should start with '# '
plugins/EQ_Alert.py:114:56: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:114:57: E262 inline comment should start with '# '
plugins/EQ_Alert.py:116:56: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:116:57: E262 inline comment should start with '# '
plugins/EQ_Alert.py:118:56: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:118:57: E262 inline comment should start with '# '
plugins/EQ_Alert.py:120:58: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:120:59: E262 inline comment should start with '# '
plugins/EQ_Alert.py:122:22: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:122:23: E262 inline comment should start with '# '
plugins/EQ_Alert.py:131:44: E713 test for membership should be 'not in'
plugins/EQ_Alert.py:140:68: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:140:69: E262 inline comment should start with '# '
plugins/EQ_Alert.py:164:9: F841 local variable 'ETag_Header' is assigned to but never used
plugins/EQ_Alert.py:170:9: F841 local variable 'Modified_time' is assigned to but never used
plugins/EQ_Alert.py:178:57: E261 at least two spaces before inline comment
plugins/EQ_Alert.py:178:58: E262 inline comment should start with '# '